### ISSUE TITLE
First cell is scrolled slightly up the drop down view initially. Any Solution?

### ISSUE THREAD

**Issue by bhallamohit** [AssistoLab/DropDown#49] opened 2016-10-02 10:12 UTC

**Comment by kevin-hirsch** [comment] 2016-10-05 13:50
Hello @bhallamohit!

Could you be more precise, please ?
And add a screenshot of the problem you have ?
👍

**Comment by bhallamohit** [comment] 2016-10-06 05:02
@kevin-hirsch  OK thanx for you reply

**Comment by bhallamohit** [comment] 2016-10-26 10:04
Any Update?

**Comment by pescadjiam** [comment] 2016-11-03 16:54
Hey @bhallamohit, have you fixed that ?

**Comment by simmyg89** [comment] 2016-11-07 17:09
The problem is in the selectRow function:

```
public func selectRow(at index: Index?) {
		if let index = index {
			tableView.selectRow(
				at: IndexPath(row: index, section: 0),
				animated: false,
				scrollPosition: .middle)
		} else {
			deselectRow(at: selectedRowIndex)
		}

		selectedRowIndex = index
	}
```

Setting scrollPosition from .middle to .top will solve the issue.
Created pull request #60

**Comment by Droppix** [comment] 2017-05-31 08:28
+1

**Comment by bhallamohit** [comment] 2017-05-31 08:47
thanks issue resolved :)

**Comment by kevin-hirsch** [comment] 2017-11-11 21:59
Hello everyone!
#77 is merged and should resolve this issue 😉

**Closed by kevin-hirsch** 2017-11-11 21:59 UTC
